# Site settings
title: NESCLiC
github_username: JoshuaDull
description: >
 New England Software Carpentry Library Consortium
url: "https://nesclic2021web.github.io"

# Build settings
markdown: kramdown
theme: minima


github_repo: nesclic2021web.github.io

integration_spreadsheet_key: 1r6tughs2XrcV4C5PC1r3NWLqwmLVHY4SWjSCkLld6ws
