# Site settings
title: New England Software Carpentry Library Consortium
github_username: NESCLiC
description: >
  NESCLiC
 
url: "https://nesclic.github.io/website"

# Build settings
markdown: kramdown
theme: minima
