# Site settings
title: NESCLiC
github_username: oelker
description: >
 New England Software Carpentry Library Consortium
url: "https://nesclic2021web.github.io"

# Build settings
markdown: kramdown
theme: minima


github_repo: nesclic2021web.github.io

integration_spreadsheet_key: AIzaSyDyi-jqCW2mlmc0687QIstJ48iQl6o3S1A
